import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {
  Button,
  Text,
  Input,
  DropDown,
  DropDownWrapper,
} from '../components/uikit/uikit';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Something here</div>
    </div>
  );
};

export default Home;
